#!/usr/bin/env python3

import sys

sin_response_dict = {
	"001": "I reserved or harbored hatred for God",
	"002": "I disobeyed the commandments of God or the church",
	"003": "I refused to accept what God has revealed as true, or what the Catholic Church proclaims for belief",
	"004": "I denied the existence of God",
	"005": "I neglected to nourish and protect my faith",
	"006": "I neglected to reject everything opposed to a sound faith",
	"007": "I deliberately misled others about doctrine or the faith",
	"008": "I rejected the Catholic faith, joined another Christian denomination, or joined or practiced another religion",
	"009": "I joined a group forbidden to Catholics",
	"010": "I despaired about my salvation or the forgiveness of my sins",
	"011": "I presumed God’s mercy",
	"012": "I loved someone or something more than God",
	"013": "I let someone or something influence my choices more than God",
	"014": "I engaged in superstitious practices",
	"015": "I have been involved in the occult or occult practices",
	"016": "I formally attempted to leave the Catholic Church",
	"017": "I have hidden a serious sin or told a lie in confession",
	"018": "I used the name of God in cursing or blasphemy",
	"019": "I failed to keep vows, promises, or resolutions that I have made to God",
	"020": "I spoken about the faith, the church, the saints, or sacred things with irreverence, hatred or defiance",
	"021": "I watched television or movies, or listened to music that treated God, the church, the saints, or sacred things irreverently",
	"022": "I used vulgar, suggestive or obscene speech",
	"023": "I belittled others in my speech",
	"024": "I behaved disrespectfully in the church building",
	"025": "I misused places or things set apart for the worship of God",
	"026": "I committed perjury",
	"027": "I blamed God for my failings",
	"028": "I missed mass on Sunday or holy days",
	"029": "I neglected to set time aside each day for personal prayer to God",
	"030": "I committed a sacrilege against the blessed sacrament",
	"031": "I received a sacrament while in the state of mortal sin",
	"032": "I habitually come late to and/or leave early from mass",
	"033": "I shop/labor/practice sports/do business unnecessarily on Sunday or other holy days of obligation",
	"034": "I have not attended to taking my children to mass",
	"035": "I have not provided proper instruction in the faith to my children",
	"036": "I have knowingly eaten meat on a forbidden day",
	"037": "I have eaten or drunken within one hour of receiving communion",
	"038": "I have not obeyed all that my parents reasonably asked of me",
	"039": "I have shown disregard for my parents wishes, displayed contempt of their demands, and/or disdained their very being",
	"040": "I neglected the needs of my parents in their old age or in their time of need",
	"041": "I harbored hatred for my parents",
	"042": "I brought shame on my parents",
	"043": "I disobeyed the reasonable demands of my teachers",
	"044": "I disrespected my teachers",
	"045": "I have neglected to give my children proper food, clothing, shelter, education, discipline and care",
	"046": "I have not provided for the religious education and formation of my children for as long as they are under my care",
	"047": "I have not ensured that my children still under my care regularly frequent the sacraments of penance and holy communion",
	"048": "I have not educated my children in a way that corresponds to Catholic religious disciplines",
	"049": "I have not provided my children with a positive, prudent and personalized education in the Catholic teaching on human sexuality",
	"050": "I have not been to my children a good example of how to live the Catholic faith",
	"051": "I have not prayed with and for my children",
	"052": "I have not lived in humble obedience to those who legitimately exercise authority over me",
	"053": "I have broken any just law",
	"054": "I have supported or voted for a politician whose positions are opposed to the teachings of Christ and the Catholic Church",
	"055": "I failed to pray for the deceased members of my family",
	"056": "I unjustly and intentionally killed a human being",
	"057": "I have been guilty, through negligence and/or lacking of intention, of the death of another",
	"058": "I been involved in an abortion, directly or indirectly",
	"059": "I seriously considered or attempted suicide",
	"060": "I supported, promoted, or encouraged the practice of assisted suicide or mercy killing",
	"061": "I deliberately desired to kill an innocent human being",
	"062": "I unjustly inflicted bodily harm on another person",
	"063": "I unjustly threatened another person with bodily harm",
	"064": "I verbally or emotionally abused another person",
	"065": "I gossiped, slandered, detracted, calumniated",
	"066": "I hated another person, or wished him/her evil",
	"067": "I been prejudiced, or unjustly discriminated against others because of their race, color, nationality, sex or religion",
	"068": "I joined a hate group",
	"069": "I purposely provoked another by teasing or nagging",
	"070": "I recklessly endangered my life or health, or that of another, by my actions",
	"071": "I have driven recklessly or under the influence of alcohol or other drugs",
	"072": "I abused alcohol or other drugs",
	"073": "I have sold or given drugs to others to use for non-therapeutic purposes",
	"074": "I used tobacco immoderately",
	"075": "I have over-eaten",
	"076": "I encouraged others to sin by giving scandal",
	"077": "I helped another to commit a mortal sin",
	"078": "I caused serious injury of another by criminal neglect",
	"079": "I indulged in unjust anger",
	"080": "I refused to control my temper",
	"081": "I been fateful to, quarreled with, or willfully hurt someone",
	"082": "I been unforgiving of others, especially when mercy or pardon was requested",
	"083": "I sought revenge or hoped something bad would happen to someone",
	"084": "I delighted to see someone else get hurt or suffer",
	"085": "I treated animals cruelly, causing them to suffer or die needlessly",
	"086": "I neglected to practice and grow in the virtue of chastity",
	"087": "I have given in to lust",
	"088": "I used an artificial means of birth control",
	"089": "I refused to be open to conception, without just cause",
	"090": "I participated in immoral techniques such as in vitro fertilization or artificial insemination",
	"091": "I sterilized my sex organs for contraceptive purposes",
	"092": "I deprived my spouse of the marital right, without just cause",
	"093": "I claimed my own marital right without concern for my spouse",
	"094": "I deliberately caused male climax outside of normal sexual intercourse",
	"095": "I willfully entertained impure thoughts",
	"096": "I purchased, viewed, or made use of pornography",
	"097": "I watched or promoted movies and television that involve sex and nudity",
	"098": "I listened to music or jokes that are harmful to purity/read books that are immoral",
	"099": "I committed adultery",
	"100": "I committed incest",
	"101": "I committed fornication",
	"102": "I engaged in homosexual activity",
	"103": "I committed rape",
	"104": "I engaged in sexual foreplay reserved for marriage",
	"105": "I preyed upon children or youth for my sexual pleasure",
	"106": "I engaged in unnatural sexual activities",
	"107": "I engaged in prostitution, or paid for the services of a prostitute",
	"108": "I seduced someone, or allowed myself to be seduced",
	"109": "I made uninvited and unwelcome sexual advances toward another",
	"110": "I purposely dressed immodestly",
	"111": "I have stolen",
	"112": "I envied others on account of their possessions",
	"113": "I neglected to live in a spirit of gospel poverty and simplicity",
	"114": "I neglected to give generously to others in need",
	"115": "I have not considered that God has provided me with money so that I might use it to benefit others, as well as for my own legitimate needs",
	"116": "I allowed myself to be conformed to a consumer mentality",
	"117": "I neglected to practice the corporal works of mercy",
	"118": "I deliberately defaced, destroyed or lost another’s property",
	"119": "I cheated on a test, taxes, sports, games, or in business",
	"120": "I squandered money in compulsive gambling",
	"121": "I make a false claim to an insurance company",
	"122": "I have not paid my employees a living wage, or failed to give a full day’s work for a full day’s pay",
	"123": "I failed to honor my part of a contract",
	"124": "I failed to make good on a debt",
	"125": "I overchargeid someone to take advantage of another’s hardship or ignorance",
	"126": "I misused natural resources",
	"127": "I lied",
	"128": "I knowingly and willfully deceived another",
	"129": "I perjured myself under oath",
	"130": "I gossiped",
	"131": "I committed detraction",
	"132": "I committed slander or calumny",
	"133": "I committed libel",
	"134": "I been guilty of rash judgment",
	"135": "I failed to make reparation for a lie I told, or for harm done to a person’s reputation",
	"136": "I failed to speak out in defense of the Catholic faith, the church, or of another person",
	"137": "I betrayed another’s confidence through speech, deed, or in writing",
	"138": "I have not attended mass on Sundays and holy days of obligation and rested from servile labor.",
	"139": "I have not made a good confession of my mortal sins at least once a year",
	"140": "I have purposely omitted telling my mortal sins in my last confession",
	"141": "I neglected to perform the penance I was given",
	"142": "I neglected to make reparation for any harm I have done to others",
	"143": "I neglected to fulfill my easter duty to receive holy communion at least once between the first Sunday of lent and trinity Sunday",
	"144": "I received holy communion while in the state of mortal sin",
	"145": "I failed to fast for at least one hour before receiving holy communion",
	"146": "I received holy communion more than twice in one day",
	"147": "I neglected to do penance every Friday of the year, if not abstaining from meat",
	"148": "I neglected to abstain from meat on Ash Wednesday and the Fridays of lent",
	"149": "I neglected to fast on Ash Wednesday and good Friday",
	"150": "I participated in diversions on days of penance",
	"151": "I neglected to spend time in prayer, do spiritual and corporal works of mercy, and practice self-denial",
	"152": "I neglected to contribute a just amount of my time, talents and money to support my parish and the work of the church",
	"153": "I neglected to support the church by not trying to become a saint or by not striving to make sincere progress each day in sanctity",
	"154": "I have been living in a invalid and/or illicit marriage according to the laws of the Catholic Church",
	"155": "I abandoned my spouse and/or family by separation or divorce",
	"156": "I kept company with someone whom I cannot marry in the Catholic Church",
	"157": "I have given scandal by living with a member of the opposite sex without the benefit of a marriage blessed by the Catholic Church",
	"158": "I entered into marriage with more than one person at the same time",
	"159": "I failed to embrace the teachings regarding marriage given by the Catholic Church, which are supported by the natural law",
	"160": "I supported pro same-sex union politicians",
	"161": "I publicly proclaimed that the church’s teaching on marriage is wrong and as such taught others to reject it"
}

script_start = "CONFESSION SCRIPT\n\n1. You may kneel at the screen or sit to talk face-to-face with the priest. It is your choice.\n\n2. Make the sign of the cross, \"In the name of the Father, and of the Son, and of the Holy Spirit.\"\n\n3. State how long it has been since your last Confession: \"Bless me Father for I have sinned. My last confession was __ days/weeks/months/years ago.\"\n\n4. Recite your sins as listed below:" 

script_end = "\n5. When finished say, \"I am sorry for all of these sins.\"\n\n6. Listen to the Priest. He will assign you some penance, provide advice, then absolve you of your sins.\n\n7. Act of Contrition: When invited by the priest, give the following Act of Contrition\n\tMy God,\n\tI am sorry for my sins with all my heart.\n\tIn choosing to do wrong\n\tand failing to do good,\n\tI have sinned against you\n\twhom I should love above all things.\n\tI firmly intend, with your help,\n\tto do penance,\n\tto sin no more,\n\tand to avoid whatever leads me to sin.\n\tOur Savior Jesus Christ suffered and died for us.\n\tIn his name, my God, have mercy.\n\n8. Do your penance as instructed by the priest."

print(script_start)

for line in sys.stdin:
    if line.startswith("[X]"):
        number_string = line[4:7]
        print("\t" + sin_response_dict[number_string])

print(script_end)
